# SwiftLint Configuration for MLXEngine

# File paths to include/exclude
included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - docs
  - sample-code
  - _docs

# Disabled rules
disabled_rules:
  - trailing_whitespace # Handled by editor
  - file_length # Some files legitimately need to be longer
  - function_body_length # Some functions legitimately need to be longer
  - cyclomatic_complexity # We prefer readability over artificial complexity limits

# Enabled opt-in rules
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - to
    - at
    - in
    - on
    - up
    - url
    - api
    - mlx
    - llm
    - vlm
    - gpu
    - cpu

nesting:
  type_level:
    warning: 2
    error: 3

closure_body_length:
  warning: 30
  error: 50

enum_case_associated_values_count:
  warning: 5
  error: 6

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  # Require mark comments for major sections
  mark_sections:
    name: "MARK Comments"
    regex: '(class|struct|enum|extension|protocol)\s+\w+.*\{\s*\n(?!\s*\/\/\s*MARK)'
    message: "Types should have MARK comments for organization"
    severity: warning

  # Discourage force unwrapping in production code
  no_force_unwrap_production:
    name: "No Force Unwrapping"
    regex: '!\s*(?!\/\/|$)'
    match_kinds:
      - identifier
    message: "Avoid force unwrapping. Use safe unwrapping instead"
    severity: warning
    excluded:
      - "Tests/*"
      - "Examples/*"

  # Require documentation for public APIs
  public_documentation:
    name: "Public API Documentation"
    regex: '^(\s*)public\s+(class|struct|enum|protocol|func|var|let)(?!\s*\/\/\/)'
    message: "Public APIs should have documentation comments"
    severity: warning
    excluded:
      - "Tests/*"
      - "Examples/*"

# Reporter
reporter: "xcode" 