name: MLXChatApp
options:
  bundleIdPrefix: com.clevercoding
  deploymentTarget:
    iOS: '17.0'
    macOS: '13.0'
    tvOS: '16.0'
    watchOS: '9.0'
    visionOS: '1.0'
packages:
  MLXEngine:
    path: ../
  SwiftUIKit:
    path: ../../swift-uikit

targets:
  MLXChatApp-iOS:
    type: application
    platform: iOS
    sources: [Sources/Shared, Sources/iOS, Sources/MLXChatApp]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      DEVELOPMENT_TEAM: M3W42R75UU
      PRODUCT_BUNDLE_IDENTIFIER: com.clevercoding.MLXChatApp-iOS
    dependencies:
      - package: MLXEngine
      - package: SwiftUIKit
    info:
      path: Sources/iOS/Info.plist
  MLXEngineTests:
    type: bundle.unit-test
    platform: macOS
    sources: [../Tests/MLXEngineTests]
    dependencies:
      - package: MLXEngine
    settings:
      ENABLE_TEST_DISCOVERY: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ../Tests/MLXEngineTests/Info.plist
  MLXChatAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [../Tests/MLXChatAppUITests]
    dependencies:
      - target: MLXChatApp-iOS
    settings:
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: ../Tests/MLXChatAppUITests/Info.plist

workspace:
  name: MLXChatApp
  projects:
    - MLXChatApp.xcodeproj 